name: Bug report
description: Report a reproducible defect in ReddMobile.
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the current behavior.
      placeholder: What is happening?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Describe what should happen instead.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Provide exact steps to reproduce.
      placeholder: |
        1. Open ...
        2. Tap ...
        3. Observe ...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App / commit version
      placeholder: v0.14.21 or commit SHA
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Device, OS, Flutter version, branch.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant logs, stack traces, or screenshots.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and did not find a duplicate.
          required: true
        - label: I removed sensitive/private information from logs.
          required: true
